//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZBlocker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EZBlocker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Block Banner Ads.
        /// </summary>
        internal static string BlockBannersCheckboxText {
            get {
                return ResourceManager.GetString("BlockBannersCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You may need to restart Spotify or your computer for this setting to take effect..
        /// </summary>
        internal static string BlockBannersRestart {
            get {
                return ResourceManager.GetString("BlockBannersRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enabling/Disabling this option requires Administrator privileges.
        ///
        ///Please reopen EZBlocker with &quot;Run as Administrator&quot;..
        /// </summary>
        internal static string BlockBannersUAC {
            get {
                return ResourceManager.GetString("BlockBannersUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EZBlocker is hidden. Double-click this icon to restore..
        /// </summary>
        internal static string HiddenNotify {
            get {
                return ResourceManager.GetString("HiddenNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spotify ads will not be muted if EZBlocker is not running.
        ///
        ///Are you sure you want to exit?.
        /// </summary>
        internal static string OnExitMessageBox {
            get {
                return ResourceManager.GetString("OnExitMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error patching Spotify. EZBlocker may not work..
        /// </summary>
        internal static string PatchErrorMessageBox {
            get {
                return ResourceManager.GetString("PatchErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EZBlocker Version: {0}
        ///Spotify Version: {1}.
        /// </summary>
        internal static string ReportProblemClipboard {
            get {
                return ResourceManager.GetString("ReportProblemClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This verison has been modified by TiB and has no link or anything with the original developer Eric Zhang.
        ///
        ///Please leave a comment clearly describing your problem.
        ///
        ///Paste this information (already copied to your clipboard):
        ///EZBlocker Version: {0}
        ///Spotify Version: {1}.
        /// </summary>
        internal static string ReportProblemMessageBox {
            get {
                return ResourceManager.GetString("ReportProblemMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Spotify with EZBlocker.
        /// </summary>
        internal static string SpotifyCheckboxText {
            get {
                return ResourceManager.GetString("SpotifyCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spotify is not installed or you have the Windows Store version.
        ///
        ///Click &apos;OK&apos; to install the normal desktop version of Spotify..
        /// </summary>
        internal static string SpotifyNotFoundMessageBox {
            get {
                return ResourceManager.GetString("SpotifyNotFoundMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start EZBlocker on Login.
        /// </summary>
        internal static string StartupCheckboxText {
            get {
                return ResourceManager.GetString("StartupCheckboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string StatusLabelLoadingText {
            get {
                return ResourceManager.GetString("StatusLabelLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Muting:.
        /// </summary>
        internal static string StatusMuting {
            get {
                return ResourceManager.GetString("StatusMuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spotify not found.
        /// </summary>
        internal static string StatusNotFound {
            get {
                return ResourceManager.GetString("StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spotify is paused.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playing:.
        /// </summary>
        internal static string StatusPlaying {
            get {
                return ResourceManager.GetString("StatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string ToolStripExit {
            get {
                return ResourceManager.GetString("ToolStripExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show EZBlocker Window.
        /// </summary>
        internal static string ToolStripOpen {
            get {
                return ResourceManager.GetString("ToolStripOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove EZBlocker from Spotify.
        /// </summary>
        internal static string ToolStripRemovePatch {
            get {
                return ResourceManager.GetString("ToolStripRemovePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open EZBlocker Website.
        /// </summary>
        internal static string ToolStripWebsite {
            get {
                return ResourceManager.GetString("ToolStripWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Translated by Eric Zhang.
        /// </summary>
        internal static string TranslatedByText {
            get {
                return ResourceManager.GetString("TranslatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to remove EZBlocker from Spotify..
        /// </summary>
        internal static string UndoPatchFailMessageBox {
            get {
                return ResourceManager.GetString("UndoPatchFailMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EZBlocker removed from Spotify..
        /// </summary>
        internal static string UndoPatchOKMessageBox {
            get {
                return ResourceManager.GetString("UndoPatchOKMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error checking for update..
        /// </summary>
        internal static string UpgradeErrorMessageBox {
            get {
                return ResourceManager.GetString("UpgradeErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is a newer version of EZBlocker available. Would you like to upgrade?.
        /// </summary>
        internal static string UpgradeMessageBox {
            get {
                return ResourceManager.GetString("UpgradeMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Volume Control.
        /// </summary>
        internal static string VolumeMixerButtonText {
            get {
                return ResourceManager.GetString("VolumeMixerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not open Volume Control.
        /// </summary>
        internal static string VolumeMixerOpenError {
            get {
                return ResourceManager.GetString("VolumeMixerOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report Problem.
        /// </summary>
        internal static string WebsiteLinkText {
            get {
                return ResourceManager.GetString("WebsiteLinkText", resourceCulture);
            }
        }
    }
}
